### ISSUE TITLE
[Feature Request] Integration with Wallabag

### ISSUE THREAD

**Issue by ojhernandez** [nov1n/RemarkablePocket#1]
I love this project and think it's great!

I It would be cool if it could be used with Pocket alternative [Wallabag](https://github.com/wallabag/wallabag) too. That way, all aspects of it could be self hosted!

Adding here after being asked to on [reddit](https://www.reddit.com/r/RemarkableTablet/comments/qtsopq/synchronize_pocket_articles_with_the_remarkable/hkmw5qs/?context=3.).

**Comment by Trisk3lion** [comment]
Would love to see support for Wallabag!

**Comment by nov1n** [comment]
I do not personally use Wallabag, so realistically I don't think I will add support for it.

If someone else wants to give it a try let me know.
