### ISSUE TITLE
README specifies use of 0.2.1 but 0.2.2 appears released

### ISSUE THREAD

**Issue by daguar** [nov1n/RemarkablePocket#14]
Hello! The README's "Usage" section references 0.2.1 in the command itself, but it appears in releases that 0.2.2 is available. Feel free to close if I'm misunderstood, but opening in case it's actually an issue!

**Comment by nov1n** [comment]
Hi, I'm testing some solutions in 0.2.2 to address #11, so I recommend using 0.2.1 for now.
