### ISSUE TITLE
[Feature Request] Support for Raspberry Pi

### ISSUE THREAD

**Issue by Raiders95** [nov1n/RemarkablePocket#2]
Awesome project!  When I tried running this via VNC into my Raspberry Pi 4B, I get the following error:

_Status: Downloaded newer image for ghcr.io/nov1n/remarkable-pocket:0.0.3

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested

standard_init_linux.go:228: exec user process caused: exec format error_

Would appreciate if you can support Raspberry Pi!  Thanks!

**Comment by nov1n** [comment]
Raspberry Pi support is available in #7
