### ISSUE TITLE
failed to create a new device token

### ISSUE THREAD

**Issue by nov1n** [nov1n/RemarkablePocket#20]
It seems like Remarkable changed something on their side causing new authentication requests to fail. Other projects are also having this problem:
- https://github.com/jelleschutter/remarkable-firefox/issues/9
- https://github.com/juruen/rmapi/issues/283

We'll have to wait for `rmapi` to fix this issue.

**Comment by ccauet** [comment]
Quick hack for the impatient:

Use [rmapi](https://github.com/juruen/rmapi) for the pairing:

- Follow the instructions, e.g. to [run it as a container](https://github.com/juruen/rmapi#docker)
- Then copy the content from `$HOME/.config/rmapi` into your  `$HOME/.rmapi` as used by RemarkablePocket

After that you can run RemarkablePocket following the README and it should work

**Comment by nov1n** [comment]
I created a new version of `RemarkablePocket` (`ghcr.io/nov1n/remarkable-pocket:0.4.0`) with `v0.0.23` of `rmapi`. However, if you're running version 3.0.0 or above on your tablet this will not work correctly because they changed the document format. Until `rmapi` supports it we'll just have to wait.
