### ISSUE TITLE
Add SSH tunnel instructions to README.md

### ISSUE THREAD

**Issue by jnissin** [nov1n/RemarkablePocket#26]
Hey!

Thanks for a great piece of software, I am really enjoying reading my pocket articles from my reMarkable. I have a slight addition to the setup process if I may. Currently, for Raspberry Pi the instructions state that:

> ... You do need a browser to complete the authentication flow. If your Pi runs without a screen I recommend using a VNC client when running the program for the first time.

I suggest that you could add that for users using Raspberry Pi via SSH: You can simply create a SSH tunnel for to the Raspberry Pi so you can avoid installing and enabling VNC. You can do this by running the following on the host computer:

```
ssh -L 65112:localhost:65112 <rpi username>@<rpi ip address>
```

After this you can proceed with the initial run Docker command and simply copy paste the authentication URL from the terminal to the host machine's browser. The redirect will be tunneled to the Raspberry Pi via the SSH tunnel.

I successfully used this method myself.

**Comment by nov1n** [comment]
Hi! This is a great idea. Do you want to create a pull request? (:
