### ISSUE TITLE
article-limit and interval from docker compose

### ISSUE THREAD

**Issue by reticle5** [nov1n/RemarkablePocket#29]
Title pretty much sums it up. I'd like to change the article-limit but I'm running RemarkablePocket from docker compose. So is there a way to set this in the docker-compose.yml ? Same for interval.

**Comment by nov1n** [comment]
Hi,

In `docker compose` you can pass commandline flags to the application as follows:

```docker-compose.yml
services:
  remarkable-pocket:
    image: ghcr.io/nov1n/remarkable-pocket:0.4.0
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - 65112:65112
    volumes:
      - ~/.remarkable-pocket:/root/.remarkable-pocket
      - ~/.rmapi:/root/.rmapi
      - ~/.rmapi-cache:/root/.cache/rmapi
    command: ["-l", "15", "-i", "30m"]
```

This will increase the limit to 15 articles, and reduce the interval to 30 minutes.

**Comment by reticle5** [comment]
Brilliant. Worked like a charm.

**Comment by nov1n** [comment]
Great to hear :) Feel free to close the issue if your problem is resolved.

**Comment by reticle5** [comment]
Thanks again.
