### ISSUE TITLE
running in azure cloud

### ISSUE THREAD

**Issue by fredboulanger** [nov1n/RemarkablePocket#3]
Hi, thanks for doing this utility - it is super useful. 
I'm trying to run this on a linux VM in the cloud.
The pocket authorization doesn't go through, because the link to visit refers to localhost.
I ssh into linux VM, then click the getpocket authorization link, it pops a local browser, hence the mismatch I'm assuming. 

Any idea how I could resolve that issue, and authorize my VM, and not the local machine on which the browser is running?

**Comment by nov1n** [comment]
Hi Fred. The oauth flow requires a browser, so I see three options:
- Complete the authorization on your local machine and copy the `~/.remarkable-pocket` file to the VM.
- Enable port forwarding on your virtual machine, and visit the localhost URL from your local machine through the forwarded port.
- Connect to your VM through a remote desktop solution such as `VNC` and complete the authorization process as you would do locally.

I have never tried any of these, so let me know if it works so I can add the instructions to the `README`.

**Comment by nov1n** [comment]
I will close this issue for inactivity. Feel free to reopen.
