### ISSUE TITLE
Running into this

### ISSUE THREAD

**Issue by drssrb90** [nov1n/RemarkablePocket#6]
Hi,
Very interested in your application!
I'm a total noob in this, but I'm running into this (can you help me out?):

Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nl.carosi.remarkablepocket.RemarkableService': Invocation of init method failed; nested exception is java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "es.jlarriba.jrmapi.Jrmapi.listDocs()" is null

**Comment by nov1n** [comment]
Hi, this is a known issue - see https://github.com/nov1n/RemarkablePocket/issues/5. Unfortunately Remarkable is rolling out a new sync protocol which is not yet supported by this application. I am still on the old version, but as soon as I get the upgrade, I'll see if I can support it.

Unfortunately there is currently no way for you to run it, but I encourage you to keep an eye on the ticket I linked.

**Comment by drssrb90** [comment]
Ok, thanks a lot! I'll indeed keep an eye on it
