### ISSUE TITLE
Please use PocketItem.getItemId() to reference Pocket articles.

### ISSUE THREAD

**Issue by testingtony** [nov1n/RemarkablePocket#8]
https://github.com/nov1n/RemarkablePocket/blob/a1aadf2611ee67042d51152f19aeed1e654159fa/src/main/java/nl/carosi/remarkablepocket/PocketService.java#L43

There are some instances where the Resolved ID is different to the Item ID, and does not work with the call to modify/archive the article. (although the [Pocket API](https://getpocket.com/developer/docs/v3/retrieve) still says it worked) 

Many thanks,
Tony.

https://github.com/tchudyk/pocket-integration/blob/4ba9851295197e6199edc0ecb03896d4e74bf7d7/src/main/java/pl/codeset/pocket/read/PocketItem.java#L73

**Comment by nov1n** [comment]
Hi Tony. I missed that part of the docs. Thanks for hunting this one down! That might explain your earlier [issue](https://github.com/nov1n/RemarkablePocket/issues/5#issuecomment-1235842124). I released a new version (0.2.1) in #10. Let me know if that solves your issue!

**Comment by testingtony** [comment]
Thanks Robert, #10 has resolved the issue with resyncying old content. Thank you for the great piece of software.

**Comment by nov1n** [comment]
I'm happy to hear that!
